### PR TITLE
add description for restart and restage

### PR DESCRIPTION
**Pull request by mastertinner**
add descriptions for the `cf restart` and `cf restage` commands since the difference between the two is not clear to new users

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @mastertinner 
This is helpful.

**Comment by mastertinner** [comment]
Thanks, @jncd. My changes were reverted by @cf-pub-tools right after you merged them (f142321). Do you know why?

**Comment by jncd** [comment]
V. odd. Thanks for letting me know. I'll investigate.

**Comment by jbheron** [comment]
Hi, @mastertinner, thanks for the PR. I'm working with @jncd, and following up about the revert to your PR. The docs for the `cf-help.html.md.erb` page are autogenerated from the actual output of the `cf help` command, which changes fairly regularly. As such, a PR here will be overwritten the next time the CLI team updates their help text. I believe that text is here: https://github.com/cloudfoundry/cli/blob/9eabfde37db06eef1f0bcb34d59f1bc45018f730/commands/v2/help_command.go

**Comment by mastertinner** [comment]
Thanks for investigating, @jncd and @jbheron! I'll make another PR for the CLI then.

**Comment by mastertinner** [comment]
I just created https://github.com/cloudfoundry/cli/pull/959 as the equivalent to this PR.

**Pull request merged**
